image: anandbose16/android-sdk:34
build-lint-test:
  script:
    - gradle clean :app:assembleDebug :app:lintDebug :app:testDebugUnitTest
  artifacts:
    untracked: false
    when: on_success
    expire_in: "30 days"
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
      - app/build/reports