trigger:
  - main
pool:
  vmImage: ubuntu-latest

container:
  image: anandbose16/android-sdk:34

steps:
  - script: gradle clean :app:assembleDebug :app:lintDebug :app:testDebugUnitTest
    displayName: Assemble, lint & execute unit tests
  - task: PublishBuildArtifacts@1
    displayName: APK file
    inputs:
      PathtoPublish: app/build/outputs/apk/debug/app-debug.apk
      ArtifactName: app-build
  - task: PublishBuildArtifacts@1
    displayName: Lint and unit test reports
    inputs:
      PathtoPublish: app/build/reports
      ArtifactName: reports