trigger:
  - main
pool:
  vmImage: ubuntu-latest

container:
  image: anandbose16/android-sdk:34

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle_user_home

steps:
  - task: Cache@2
    inputs:
      key: '"gradle-user-home" | "$(Agent.OS)" | cache-id'
      restoreKeys: |
        "gradle-user-home" | "$(Agent.OS)"
        "gradle-user-home"
      path: $(GRADLE_USER_HOME)
  - script: gradle --build-cache --configuration-cache --parallel clean :app:assembleDebug :app:lintDebug :app:testDebugUnitTest
    displayName: Assemble, lint & execute unit tests
  - task: PublishBuildArtifacts@1
    displayName: APK file
    inputs:
      PathtoPublish: app/build/outputs/apk/debug/app-debug.apk
      ArtifactName: app-build
  - task: PublishBuildArtifacts@1
    displayName: Lint and unit test reports
    inputs:
      PathtoPublish: app/build/reports
      ArtifactName: reports