image: anandbose16/android-sdk:34

pipelines:
  default:
    - step:
        name: Assemble, lint and run unit tests
        caches:
          - "gradle"
        script:
          - gradle clean :app:assembleDebug :app:lintDebug :app:testDebugUnitTest
        artifacts:
          - "app/build/outputs/apk/debug/app-debug.apk"
          - "app/build/reports"