name: Build and test
on:
    push:
        branches: [ main ]
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        container: 
            image: anandbose16/android-sdk:34
            options: --device=/dev/kvm
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build, lint, execute unit tests and instrumented tests
              run: gradle clean :app:assembleDebug :app:lintDebug :app:testDebugUnitTest :app:mediumPhoneApi34AospAtdDebugAndroidTest
            - name: Upload Build
              uses: actions/upload-artifact@v4
              with:
                name: 'build'
                path: app/build/outputs/apk/debug/app-debug.apk
            - name: Upload lint and test reports
              uses: actions/upload-artifact@v4
              with:
                name: reports
                path: app/build/reports